### ISSUE TITLE
Unable to release machine with MAAS 3.6.0

### ISSUE THREAD

**Issue by nafallo** [canonical/ansible-collection#47]
Since MAAS 3.6.0 I'm unable to put machines back to ready state. Deployment still works just fine.

```yaml
- name: Release machine
  timeout: 600
  vars:
    ansible_connection: local
  maas.maas.instance:
    fqdn: "{{ inventory_hostname }}"
    state: ready
```

```
TASK [Release machine] 
fatal: [host.maas]: FAILED! => {"changed": false, "msg": "Unexpected response - 400 b''"}
```
